title: DoctorLogic Schemas
email: rdennis@doctorlogic.com
description: >- # this means to ignore newlines until "baseurl:"
  Schema project for DoctorLogic Products. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://schema.doctorlogic.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# add /schemas as a collection
collections:
  schemas:
    output: true
    permalink: /:path